"""Render the ImHex pattern for a framed pool file.

Offsets are not written here. Every record layout comes from
`finale_file_parser.formats.layouts`, which the parser and the inspector read
too, so this pattern cannot state an offset the code does not use. What lives
here is the container walk and the two eras' record shapes, which are structure
rather than payload.
"""

from __future__ import annotations

from finale_file_parser.enigma.mus_payload import (
    POOL_DETAILS,
    POOL_ENTRIES,
    POOL_OTHERS,
    POOL_TEXT,
)
from finale_file_parser.enigma.pool_file import (
    EMPTY_ENTRY_LENGTH,
    ENTRY_HEADER_SIZE,
    ERA_DCL,
    ERA_ZLIB,
    HEADER_SIZE,
    MAGIC,
)

HEXPAT_TYPES = {
    "uint8": "u8",
    "uint16": "u16",
    "uint32": "u32",
    "int16": "s16",
    "string": "char",
}
"""Every field type the catalog uses, and the hexpat type that reads it.

`string` maps to `char` because the catalog's only string fields are
NUL-terminated tails, which hexpat writes as `char name[]`.
"""

_PREAMBLE = f"""#pragma description Finale .mus decompressed pools
#pragma magic [ {" ".join(f"{b:02X}" for b in MAGIC)} ] @ 0x00  // "{MAGIC.decode()}"

// GENERATED by scripts/hexpat -- do not edit.
//
// This pattern reads the file `finale-parser extract` writes, NOT a .mus. A
// .mus keeps its pools compressed, and the 2001-2005 era uses PKWARE implode,
// which ImHex cannot decompress. Run:
//
//     finale-parser extract score.mus     -> score.pools.bin
//
// and open that. The chain below is the .mus container's own framing -- kind,
// length, checksum -- with each payload decompressed in place.

import std.core;
import std.mem;

enum PoolKind : u16 {{
    others  = {POOL_OTHERS},
    details = {POOL_DETAILS},
    entries = {POOL_ENTRIES},
    text    = {POOL_TEXT},
}};

enum Era : u8 {{
    zlib_2011 = {ERA_ZLIB},
    dcl_2005  = {ERA_DCL},
}};

struct Header {{
    char magic[4];
    u8 version;
    u8 order;          // 0 little, 1 big -- applies to everything after this header
    Era era;
    u8 pools;
}};
"""


def render_pattern() -> str:
    """The whole pattern, as one string."""
    parts = [_PREAMBLE, _record_shapes(), _payload_structs(), _entry_point()]
    return "\n".join(parts)


def _record_shapes() -> str:
    """The two eras' record framings.

    These are not in the catalog because they are container structure rather
    than payload: the catalog describes what is *inside* a record.
    """
    return (
        """
// A 2011 pool is a run of self-identifying, variable-length records. One
// occupies 14 + length bytes for `others` and 16 + length for `details`.
struct OthersRecord {
    u16 tag;
    u16 cmper;
    u16 part;
    u32 length;
    u8 payload[length];
    u8 trailer[4];
};

struct DetailsRecord {
    u16 tag;
    u16 cmper1;
    u16 cmper2;
    u16 inci;
    u32 length;
    u8 payload[length];
    u32 extra_length;
    u8 extra[extra_length];
};

// A 2001-2005 pool is a table of fixed 16-byte rows carrying ETF's
// two-character tags. The tag is a u16, NOT two characters: on a little-endian
// file its letters come out reversed, so `^MS` is stored `SM`. Reading the pair
// verbatim finds no known tag in 102 of 139 corpus documents.
//
// A record too big for one row runs on into further rows under the same tag and
// key -- ETF calls each row an incidence -- so a row is a fragment of a record,
// not a record.
//
// Row size is enigma.mus_rows._ROW (16 bytes). The two `data` sizes below are
// that row size minus each row's prefix: 16 - 4 (cmper + tag) = 12 for
// `others`, 16 - 6 (cmper1 + cmper2 + tag) = 10 for `details` -- see
// enigma.mus_rows._OTHERS_DATA and _DETAILS_DATA, which are private to that
// module so are not imported here.
struct DclOthersRow {
    u16 cmper;
    u16 tag;
    u8 data[12];
};

struct DclDetailsRow {
    u16 cmper1;
    u16 cmper2;
    u16 tag;
    u8 data[10];
};
"""
        + f"""
struct PoolEntry {{
    PoolKind kind;
    u32 length;
    if (length != {EMPTY_ENTRY_LENGTH}) {{
        u32 checksum;   // always 0: the container's checksum covers the
                        // COMPRESSED stream, which this file does not hold
        u8 payload[length - {ENTRY_HEADER_SIZE}];
    }}
}};
"""
    )


def _entry_point() -> str:
    return f"""
Header header @ 0x00;

fn init() {{
    std::core::set_endian(
        header.order == 1 ? std::mem::Endian::Big : std::mem::Endian::Little
    );
}};

init();

PoolEntry pools[header.pools] @ {HEADER_SIZE};
"""


def _payload_structs() -> str:
    """Placeholder until Task 5; returns nothing so Task 4's tests can pass."""
    return ""
