"""Render the ImHex pattern for a framed pool file.

Offsets are not written here. Every record layout comes from
`finale_file_parser.formats.layouts`, which the parser and the inspector read
too, so this pattern cannot state an offset the code does not use. What lives
here is the container walk and the two eras' record shapes, which are structure
rather than payload.
"""

from __future__ import annotations

from finale_file_parser.enigma.mus_payload import (
    POOL_DETAILS,
    POOL_ENTRIES,
    POOL_OTHERS,
    POOL_TEXT,
)
from finale_file_parser.enigma.pool_file import (
    EMPTY_ENTRY_LENGTH,
    ENTRY_HEADER_SIZE,
    ERA_DCL,
    ERA_ZLIB,
    HEADER_SIZE,
    MAGIC,
)
from finale_file_parser.formats.layouts import LAYOUTS, Field, Layout

HEXPAT_TYPES = {
    "uint8": "u8",
    "uint16": "u16",
    "uint32": "u32",
    "int16": "s16",
    "string": "char",
}
"""Every field type the catalog uses, and the hexpat type that reads it.

`string` maps to `char` because the catalog's only string fields are
NUL-terminated tails, which hexpat writes as `char name[]`.
"""

_PREAMBLE = f"""#pragma description Finale .mus decompressed pools
#pragma magic [ {" ".join(f"{b:02X}" for b in MAGIC)} ] @ 0x00  // "{MAGIC.decode()}"

// GENERATED by scripts/hexpat -- do not edit.
//
// This pattern reads the file `finale-parser extract` writes, NOT a .mus. A
// .mus keeps its pools compressed, and the 2001-2005 era uses PKWARE implode,
// which ImHex cannot decompress. Run:
//
//     finale-parser extract score.mus     -> score.pools.bin
//
// and open that. The chain below is the .mus container's own framing -- kind,
// length, checksum -- with each payload decompressed in place.

import std.core;
import std.mem;

enum PoolKind : u16 {{
    others  = {POOL_OTHERS},
    details = {POOL_DETAILS},
    entries = {POOL_ENTRIES},
    text    = {POOL_TEXT},
}};

enum Era : u8 {{
    zlib_2011 = {ERA_ZLIB},
    dcl_2005  = {ERA_DCL},
}};

struct Header {{
    char magic[4];
    u8 version;
    u8 order;          // 0 little, 1 big -- applies to everything after this header
    Era era;
    u8 pools;
}};
"""


def render_pattern() -> str:
    """The whole pattern, as one string."""
    parts = [_PREAMBLE, _record_shapes(), _payload_structs(), _entry_point()]
    return "\n".join(parts)


def _record_shapes() -> str:
    """The two eras' record framings.

    These are not in the catalog because they are container structure rather
    than payload: the catalog describes what is *inside* a record.
    """
    return (
        """
// A 2011 pool is a run of self-identifying, variable-length records, with two
// bytes of 0x0000 / 0xFFFF filler between some of them. A record occupies
// 14 + length + extra_length bytes for `others` and 16 + length + extra_length
// for `details`.
//
// The four bytes after the payload are the LENGTH OF AN EXTRA BLOCK, not a
// fixed four-byte trailer: the trailer reading is retracted in
// docs/ARCHITECTURE.md, and enigma.mus_others._walk / mus_details._walk read
// `extra` bytes after it. The block is empty on 99.4% of records, which is why
// the trailer reading survived so long; where it is not, it is 24, 48 or 96
// bytes, and treating it as fixed desynchronizes every record after that one.
struct OthersRecord {
    u16 tag;
    if (tag != 0x0000 && tag != 0xFFFF) {
        u16 cmper;
        u16 part;
        u32 length;
        u8 payload[length];
        u32 extra_length;
        u8 extra[extra_length];
    }
    // Otherwise `tag` was two bytes of filler rather than a record header, and
    // the next record starts straight after it -- which is what the readers do,
    // and what keeps the walk in step.
};

struct DetailsRecord {
    u16 tag;
    if (tag != 0x0000 && tag != 0xFFFF) {
        u16 cmper1;
        u16 cmper2;
        u16 inci;
        u32 length;
        u8 payload[length];
        u32 extra_length;
        u8 extra[extra_length];
    }
    // Filler is skipped two bytes at a time here too.
};

// A 2001-2005 pool is a table of fixed 16-byte rows carrying ETF's
// two-character tags. The tag is a u16, NOT two characters: on a little-endian
// file its letters come out reversed, so `^MS` is stored `SM`. Reading the pair
// verbatim finds no known tag in 102 of 139 corpus documents.
//
// A record too big for one row runs on into further rows under the same tag and
// key -- ETF calls each row an incidence -- so a row is a fragment of a record,
// not a record.
//
// Row size is enigma.mus_rows._ROW (16 bytes). The two `data` sizes below are
// that row size minus each row's prefix: 16 - 4 (cmper + tag) = 12 for
// `others`, 16 - 6 (cmper1 + cmper2 + tag) = 10 for `details` -- see
// enigma.mus_rows._OTHERS_DATA and _DETAILS_DATA, which are private to that
// module so are not imported here.
struct DclOthersRow {
    u16 cmper;
    u16 tag;
    u8 data[12];
};

struct DclDetailsRow {
    u16 cmper1;
    u16 cmper2;
    u16 tag;
    u8 data[10];
};
"""
        + f"""
struct PoolEntry {{
    PoolKind kind;
    u32 length;
    if (length != {EMPTY_ENTRY_LENGTH}) {{
        u32 checksum;   // always 0: the container's checksum covers the
                        // COMPRESSED stream, which this file does not hold
        u64 payload_end = $ + length - {ENTRY_HEADER_SIZE};

        // Which shape a payload has is the header's era and this entry's kind
        // -- the same two things the parser dispatches on. `entries` and `text`
        // have no catalogued record shape, so they stay raw bytes rather than
        // being given an invented one.
        if (header.era == Era::zlib_2011 && kind == PoolKind::others) {{
            OthersRecord records[while($ < payload_end)];
        }} else if (header.era == Era::zlib_2011 && kind == PoolKind::details) {{
            DetailsRecord records[while($ < payload_end)];
        }} else if (header.era == Era::dcl_2005 && kind == PoolKind::others) {{
            DclOthersRow rows[while($ < payload_end)];
        }} else if (header.era == Era::dcl_2005 && kind == PoolKind::details) {{
            DclDetailsRow rows[while($ < payload_end)];
        }} else {{
            u8 payload[length - {ENTRY_HEADER_SIZE}];
        }}

        if ($ != payload_end) {{
            // The records did not tile the payload exactly. Skipping to the
            // entry's stated end keeps every later entry at its real offset; if
            // the walk overran instead, this length underflows and ImHex stops
            // here -- loudly, which a quietly shifted chain would not be.
            padding[payload_end - $];
        }}
    }}
}};
"""
    )


def _entry_point() -> str:
    return f"""
Header header @ 0x00;

fn init() {{
    std::core::set_endian(
        header.order == 1 ? std::mem::Endian::Big : std::mem::Endian::Little
    );
}};

init();

PoolEntry pools[header.pools] @ {HEADER_SIZE};
"""


def _payload_structs() -> str:
    """One struct per layout the catalog permits to be laid over real bytes.

    `Layout.computed` layouts are named and explained but never emitted as a
    struct: a computed layout describes a record whose field positions the
    reader works out per record or era, so pointing it at arbitrary bytes shows
    values that are confidently wrong. `report/model.py` skips them for exactly
    this reason.
    """
    names = _struct_names()
    parts = ["\n// ---- record payloads, generated from formats/layouts.py ----\n"]
    for layout in LAYOUTS:
        # `names` only holds non-computed layouts -- `_one_struct` never reads
        # its `name` argument for a computed layout, so a placeholder is enough
        # there; for anything else, indexing directly (rather than `.get` with a
        # fallback) means a layout `_struct_names` failed to name raises loudly
        # instead of silently re-emitting a colliding base name.
        name = layout.name if layout.computed else names[layout]
        parts.append(_one_struct(layout, name))
    parts.append(_tag_comment(names))
    return "\n".join(parts)


def _base_struct_name(layout: Layout) -> str:
    """The struct name a layout would get, before collisions are resolved.

    Not every `stride` layout needs the `Slot` suffix added: `LyricVerseSlot`
    and `InstUsedSlot` already carry it in the catalog's own `name`, because
    that is what the parser and the report call them too. Appending it again
    here would name the struct `LyricVerseSlotSlot`.
    """
    if not layout.stride:
        return layout.name
    return layout.name if layout.name.endswith("Slot") else f"{layout.name}Slot"


def _struct_names() -> dict[Layout, str]:
    """Every non-`computed` layout's struct name, with collisions disambiguated.

    Two eras of one record can legitimately share a catalog `name` --
    `TEXT_EXPR_DEF` and `TEXT_EXPR_DEF_DCL` both describe `textExprDef`, one per
    era -- so the base name collides on purpose, and ImHex would reject the
    resulting redefinition outright. The collision is *detected* here, not
    hardcoded to this pair, so the next one is caught the same way. `Layout.tag`
    is documented as 0 for "a layout that describes only the DCL spelling", so
    that is the member a colliding group suffixes with `Dcl`; a group this rule
    cannot make unique raises, rather than silently emitting a second collision.
    """
    groups: dict[str, list[Layout]] = {}
    for layout in LAYOUTS:
        if layout.computed:
            continue
        groups.setdefault(_base_struct_name(layout), []).append(layout)

    names: dict[Layout, str] = {}
    for base, group in groups.items():
        if len(group) == 1:
            names[group[0]] = base
            continue
        for layout in group:
            names[layout] = f"{base}Dcl" if layout.tag == 0 else base
        resolved = {names[layout] for layout in group}
        if len(resolved) != len(group):
            raise ValueError(
                f"struct name collision on {base!r} that tag==0 disambiguation cannot "
                f"resolve: {[layout.record for layout in group]}"
            )
    return names


def _one_struct(layout: Layout, name: str) -> str:
    """The struct for one layout, with the catalog's gaps rendered as `padding`.

    A layout's fields are sparse -- `StaffSpec`'s only field sits at `+20`, and
    `TextExprDef`'s tail starts at `+36` -- so writing the fields back to back
    would land every one after a gap at the wrong offset: exactly the
    "confident, wrong values" harm the `computed` guard above exists to avoid,
    just reached a different way. `padding[N]` closes each gap, and closes the
    tail of a `stride` layout too, so an array of these structs stays aligned
    slot to slot instead of drifting after the first one.
    """
    tags = _tag_names(layout)
    if layout.computed:
        return (
            f"// {layout.name} ({tags}) is NOT laid out here. Its reader works out where\n"
            f"// the fields sit per record or era, so these offsets are the shape a reader\n"
            f"// starts from rather than where the bytes are. Laying it over a record would\n"
            f"// show confident, wrong values, so the payload stays raw.\n"
        )

    lines = [f"// {layout.record} -- {tags}", f"struct {name} {{"]
    cursor = 0
    tail = False
    for field in layout.fields:
        if field.offset < cursor:
            raise ValueError(
                f"{layout.name}.{field.name} at +{field.offset} overlaps the previous "
                f"field, which runs to +{cursor}"
            )
        if field.offset > cursor:
            lines.append(f"    padding[{field.offset - cursor}];")
        lines.append(_one_field(field))
        if field.is_tail:
            tail = True
            break
        cursor = field.end
    if layout.stride and tail:
        # The slot comment below would announce fixed-size slots over a struct
        # whose length depends on its data, so every slot after the first would
        # be read at the wrong offset. Unreachable with today's catalog, and the
        # two sibling impossibilities above raise rather than emit -- so does
        # this one.
        raise ValueError(
            f"{layout.name} has both a tail field and a {layout.stride}-byte stride, "
            f"so its slots cannot be a fixed size"
        )
    if layout.stride and not tail:
        if cursor > layout.stride:
            raise ValueError(
                f"{layout.name}'s fields run past its stride: end +{cursor} > "
                f"stride {layout.stride}"
            )
        if cursor < layout.stride:
            lines.append(f"    padding[{layout.stride - cursor}];")
    lines.append("};")
    if layout.stride:
        lines.append(
            f"// {layout.name}: the payload is an array of {layout.stride}-byte "
            f"{name} slots, not one structure."
        )
    return "\n".join(lines) + "\n"


def _one_field(field: Field) -> str:
    hexpat = HEXPAT_TYPES[field.type_]
    note = f"    // {field.note}" if field.note else ""
    if field.is_tail:
        return f"    {hexpat} {field.name}[];{note}"
    if field.type_ == "string":
        return f"    {hexpat} {field.name}[{field.size}];{note}"
    return f"    {hexpat} {field.name};{note}"


def _tag_names(layout: Layout) -> str:
    both = []
    if layout.tag:
        both.append(f"tag {layout.tag}")
    if layout.dcl:
        both.append(f"DCL ^{layout.dcl}")
    return ", ".join(both) if both else "no tag"


def _tag_comment(names: dict[Layout, str]) -> str:
    """Which struct reads which tag, in both spellings.

    `PoolEntry` dispatches on era and kind, because a record's *framing* needs
    no invention. Its *payload* does: a tag this project has not decoded has no
    catalogued shape, so a generated per-tag dispatch would have to invent one
    for every unknown tag to keep the arms exhaustive. The mapping is therefore
    stated for a reader to apply by hand over a record's payload, and undecoded
    payloads stay raw bytes. Uses the same disambiguated names `_one_struct`
    actually emitted, so a reader following this mapping never lands on a struct
    name that does not exist.
    """
    lines = ["\n// ---- which struct reads which tag ----"]
    for layout in sorted(LAYOUTS, key=lambda item: (item.pool, item.tag or 0)):
        if layout.computed:
            continue
        lines.append(f"//   {layout.pool:8} {_tag_names(layout):22} -> {names[layout]}")
    lines.append(
        "// A tag not listed above has no catalogued layout: its payload stays raw bytes\n"
        "// rather than being given an invented structure.\n"
        "//\n"
        "// THE DCL ARROWS DO NOT POINT AT A ROW. In that era a record's payload is the\n"
        "// concatenation of its rows' data -- 12 bytes from each `others` row at +4, 10\n"
        "// from each `details` row at +6 -- so a struct above must be laid over that\n"
        "// gathered payload, never over a row. StaffSpec's field at +20 lives in the\n"
        "// second row's data and TextExprDefDcl's at +36 in the fourth; placed at a row\n"
        "// start, either one reads the next row's cmper and tag as a field value and\n"
        "// shows a confident, wrong number."
    )
    return "\n".join(lines) + "\n"
